---
openapi: 3.0.0
info:
  version: 0.9.0
  title: Radix Gateway API
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  "/network":
    post:
      summary: Get Network
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/NetworkRequest"
      responses:
        '200':
          description: The Network
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/NetworkResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/token":
    post:
      summary: Get Token Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TokenRequest"
      responses:
        '200':
          description: Token info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TokenResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/token/native":
    post:
      summary: Get Native Token Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TokenNativeRequest"
      responses:
        '200':
          description: Token info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TokenNativeResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/token/derive":
    post:
      summary: Derive Token Identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TokenDeriveRequest"
      responses:
        '200':
          description: Token info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TokenDeriveResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/account/balances":
    post:
      summary: Get Account Balances
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AccountBalancesRequest"
      responses:
        '200':
          description: Balances of Account
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AccountBalancesResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/account/stakes":
    post:
      summary: Get Stake Positions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AccountStakesRequest"
      responses:
        '200':
          description: List of Stake Positions
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AccountStakesResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/account/unstakes":
    post:
      summary: Get Unstake Positions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AccountUnstakesRequest"
      responses:
        '200':
          description: List of Unstake Positions
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AccountUnstakesResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/account/transactions":
    post:
      summary: Get Account Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AccountTransactionsRequest"
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AccountTransactionsResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/validator":
    post:
      summary: Get Validator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ValidatorInfoRequest"
      responses:
        '200':
          description: Validator Info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidatorInfoResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/validators":
    post:
      summary: Get Validators
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ValidatorsRequest"
      responses:
        '200':
          description: Ordered list of validators
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidatorsResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/transaction/rules":
    post:
      summary: Get Transaction Rules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionRulesRequest"
      responses:
        '200':
          description: Rules for transaction construction
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionRulesResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/transaction/build":
    post:
      summary: Build Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionBuildRequest"
      responses:
        '200':
          description: An unsigned transaction
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionBuildResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/transaction/finalize":
    post:
      summary: Finalize Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionFinalizeRequest"
      responses:
        '200':
          description: Final Signed Transaction
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionFinalizeResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/transaction/submit":
    post:
      summary: Submit Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionSubmitRequest"
      responses:
        '200':
          description: Successful Submission
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionSubmitResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
  "/transaction/status":
    post:
      summary: Get Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionStatusRequest"
      responses:
        '200':
          description: Transaction Status
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionStatusResponse"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnexpectedError"
components:
  schemas:
    AccountBalancesRequest:
      type: object
      required:
        - network
        - account_identifier
      properties:
        network:
          type: string
        account_identifier:
          "$ref": "#/components/schemas/AccountIdentifier"
      example:
        network: mainnet
        account_identifier:
          address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
    AccountBalancesResponse:
      type: object
      required:
        - ledger_state
        - account_balances
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        account_balances:
          "$ref": "#/components/schemas/AccountBalances"
      example:
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        account_balances:
          staked_and_unstaking_balance:
            amount: '0'
            token_identifier:
              rri: xrd_rr1qy5wfsfh
          liquid_balances:
            - amount: '1000000000000000000000'
              token_identifier:
                rri: xrd_rr1qy5wfsfh
    AccountBalances:
      type: object
      required:
        - staked_and_unstaking_balance
        - liquid_balances
      properties:
        staked_and_unstaking_balance:
          "$ref": "#/components/schemas/TokenAmount"
        liquid_balances:
          type: array
          items:
            "$ref": "#/components/schemas/TokenAmount"
    AccountStakesRequest:
      type: object
      required:
        - network
        - account_identifier
      properties:
        network:
          type: string
        account_identifier:
          "$ref": "#/components/schemas/AccountIdentifier"
      example:
        network: mainnet
        account_identifier:
          address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
    AccountStakesResponse:
      type: object
      required:
        - stakes
        - ledger_state
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        stakes:
          type: array
          items:
            "$ref": "#/components/schemas/AccountStakeEntry"
      example:
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        stakes:
          - validator_identifier:
              address: rv1qg923hl7f725cs06eg5gmdcy4pfvpa8mfnjcw669traquj28c96z5w0rld0
            delegated_stake:
              token_identifier:
                rri: xrd_rr1qy5wfsfh
              value: '1000000000000000000000'
    AccountStakeEntry:
      type: object
      required:
        - validator_identifier
        - delegated_stake
      properties:
        validator_identifier:
          "$ref": "#/components/schemas/ValidatorIdentifier"
        delegated_stake:
          "$ref": "#/components/schemas/TokenAmount"
    AccountUnstakesRequest:
      type: object
      required:
        - network
        - account_identifier
      properties:
        network:
          type: string
        account_identifier:
          "$ref": "#/components/schemas/AccountIdentifier"
      example:
        network: mainnet
        account_identifier:
          address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
    AccountUnstakesResponse:
      type: object
      required:
        - ledger_state
        - unstakes
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        unstakes:
          type: array
          items:
            "$ref": "#/components/schemas/AccountUnstakeEntry"
      example:
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        unstakes:
          - validator_identifier:
              address: rv1qg923hl7f725cs06eg5gmdcy4pfvpa8mfnjcw669traquj28c96z5w0rld0
            unstaking_amount:
              token_identifier:
                rri: xrd_rr1qy5wfsfh
              value: '1000000000000000000000'
            epochs_until_unlocked: 1
    AccountUnstakeEntry:
      type: object
      required:
        - validator_identifier
        - unstaking_amount
        - epochs_until_unlocked
      properties:
        validator_identifier:
          "$ref": "#/components/schemas/ValidatorIdentifier"
        unstaking_amount:
          "$ref": "#/components/schemas/TokenAmount"
        epochs_until_unlocked:
          type: integer
          format: int64
    AccountTransactionsRequest:
      type: object
      required:
        - network
        - account_identifier
      properties:
        network:
          type: string
        account_identifier:
          "$ref": "#/components/schemas/AccountIdentifier"
        cursor:
          type: string
        limit:
          type: integer
      example:
        network: mainnet
        account_identifier:
          address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
        cursor: '0'
        limit: 1
    AccountTransactionsResponse:
      type: object
      required:
        - ledger_state
        - transactions
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
          type: integer
          format: int64
        next_cursor:
          type: string
        transactions:
          type: array
          items:
            "$ref": "#/components/schemas/AccountTransaction"
      example:
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        next_cursor: 0
        transactions:
          - fee_paid:
              token_identifier:
                rri: xrd_rr1qy5wfsfh
              value: '72000000000000000'
            metadata:
              signed_by:
                hex: 02aa1c49af92a39d15257d7dc43f805f18f9f0ea712450c53e75255f5a0d1d93b6
              hex: 07030e7094728c8d065c5db696977696bea9094f67bcfd4c021f99ec784e24023b0000000c0100210000000000000000000000000000000000000000000000000000ffcb9e57d4000002004506000402aa1c49af92a39d15257d7dc43f805f18f9f0ea712450c53e75255f5a0d1d93b601000000000000000000000000000000000000000007c13bc4b1c16827082c00000008000002004506000402aa1c49af92a39d15257d7dc43f805f18f9f0ea712450c53e75255f5a0d1d93b601000000000000000000000000000000000000000007ad6192165e31dff02c000002004506000403dc62fa04804f75d009a2fac32c8ceb9dc5eaccd54934fe20ef5b86be40c7a2ab0100000000000000000000000000000000000000000013da329b63364718000000000b015584aed8375f30b22a2203b77dbe15e5dc0a3618fb45ea30ee54a6ebe0054b673a471ad2214b7bd06c4228083643b57e095787c9fb01443e1c3d6890d28f60cf
              timestamp: 1627407310726
            actions:
              - amount:
                  token_identifier:
                    rri: xrd_rr1qy5wfsfh
                  value: '24000000000000000000000000'
                from: rdx1qsp258zf47f288g4y47hm3plsp03370safcjg5x98e6j2h66p5we8ds8m7g33
                to: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
                type: TransferTokens
    TransferTokens:
      allOf:
        - "$ref": "#/components/schemas/Action"
        - type: object
          required:
            - from
            - to
            - amount
          properties:
            from:
              "$ref": "#/components/schemas/AccountIdentifier"
            to:
              "$ref": "#/components/schemas/AccountIdentifier"
            amount:
              "$ref": "#/components/schemas/TokenAmount"
    StakeTokens:
      allOf:
        - "$ref": "#/components/schemas/Action"
        - type: object
          required:
            - from
            - to
            - amount
          properties:
            from:
              "$ref": "#/components/schemas/AccountIdentifier"
            to:
              "$ref": "#/components/schemas/ValidatorIdentifier"
            amount:
              "$ref": "#/components/schemas/TokenAmount"
    UnstakeTokens:
      allOf:
        - "$ref": "#/components/schemas/Action"
        - type: object
          required:
            - from
            - to
            - amount
          properties:
            from:
              "$ref": "#/components/schemas/ValidatorIdentifier"
            to:
              "$ref": "#/components/schemas/AccountIdentifier"
            amount:
              "$ref": "#/components/schemas/TokenAmount"
    CreateTokenDefinition:
      allOf:
        - "$ref": "#/components/schemas/Action"
        - type: object
          required:
            - token_properties
            - token_supply
          properties:
            token_properties:
              "$ref": "#/components/schemas/TokenProperties"
            token_supply:
              "$ref": "#/components/schemas/TokenAmount"
            to:
              "$ref": "#/components/schemas/AccountIdentifier"
    MintTokens:
      allOf:
        - "$ref": "#/components/schemas/Action"
        - type: object
          required:
            - to
            - amount
          properties:
            to:
              "$ref": "#/components/schemas/AccountIdentifier"
            amount:
              "$ref": "#/components/schemas/TokenAmount"
    BurnTokens:
      allOf:
        - "$ref": "#/components/schemas/Action"
        - type: object
          required:
            - from
            - amount
          properties:
            from:
              "$ref": "#/components/schemas/AccountIdentifier"
            amount:
              "$ref": "#/components/schemas/TokenAmount"
    Action:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          TransferTokens: "#/components/schemas/TransferTokens"
          StakeTokens: "#/components/schemas/StakeTokens"
          UnstakeTokens: "#/components/schemas/UnstakeTokens"
          MintTokens: "#/components/schemas/MintTokens"
          BurnTokens: "#/components/schemas/BurnTokens"
    TransactionRulesRequest:
      type: object
      required:
        - network
      properties:
        network:
          type: string
      example:
        network: mainnet
    TransactionRulesResponse:
      type: object
      required:
        - ledger_state
        - transaction_rules
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        transaction_rules:
          "$ref": "#/components/schemas/TransactionRules"
    TransactionRules:
      type: object
      properties:
        maximum_message_length:
          type: integer
        minimum_stake:
          "$ref": "#/components/schemas/TokenAmount"
    TransactionBuildRequest:
      type: object
      required:
        - network
        - actions
        - fee_payer
      properties:
        network:
          type: string
        actions:
          type: array
          items:
            "$ref": "#/components/schemas/Action"
        fee_payer:
          "$ref": "#/components/schemas/AccountIdentifier"
        message:
          type: string
        disable_token_mint_and_burn:
          type: boolean
      example:
        network: mainnet
        actions:
          - type: TransferTokens
            from:
              address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
            to:
              address: rdx1qspcvwwuf8s549zyspz683v4n93g9kzpn6u6a9yalwzt00zghg75lmsftwv29
            amount:
              token_identifier:
                rri: xrd_rr1qy5wfsfh
              value: '123000000000000000'
        fee_payer:
          address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
        disable_token_mint_and_burn: true
    TransactionBuildResponse:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          TransactionBuildResponseSuccess: "#/components/schemas/TransactionBuildResponseSuccess"
          TransactionBuildResponseError: "#/components/schemas/TransactionBuildResponseError"
    TransactionBuildResponseSuccess:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildResponse"
        - type: object
          required:
            - transaction_build
          properties:
            transaction_build:
              $ref: "#/components/schemas/TransactionBuild"
    TransactionBuild:
      type: object
      required:
        - fee
        - unsigned_transaction
        - payload_to_sign
      properties:
        fee:
          "$ref": "#/components/schemas/TokenAmount"
        unsigned_transaction:
          type: string
        payload_to_sign:
          type: string
    TransactionBuildResponseError:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildResponse"
        - type: object
          required:
            - error
          properties:
            error:
              $ref: "#/components/schemas/TransactionBuildError"
    TransactionBuildError:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          NotEnoughResourcesError: "#/components/schemas/NotEnoughResourcesError"
          BelowMinimumStakeError: "#/components/schemas/BelowMinimumStakeError"
          NotValidatorOwnerError: "#/components/schemas/NotValidatorOwnerError"
          MessageTooLongError: "#/components/schemas/MessageTooLongError"
          CouldNotConstructFeesError: "#/components/schemas/CouldNotConstructFeesError"
    NotEnoughResourcesError:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildError"
        - type: object
          required:
            - requested_amount
            - available_amount
          properties:
            requested_amount:
              $ref: "#/components/schemas/BigInteger"
            available_amount:
              $ref: "#/components/schemas/BigInteger"
    BelowMinimumStakeError:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildError"
        - type: object
          required:
            - requested_amount
            - minimum_amount
          properties:
            requested_amount:
              $ref: "#/components/schemas/BigInteger"
            minimum_amount:
              $ref: "#/components/schemas/BigInteger"
    NotValidatorOwnerError:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildError"
        - type: object
          required:
            - owner
            - user
          properties:
            owner:
              $ref: "#/components/schemas/AccountIdentifier"
            user:
              $ref: "#/components/schemas/AccountIdentifier"
    MessageTooLongError:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildError"
        - type: object
          required:
            - length_limit
            - attempted_length
          properties:
            length_limit:
              type: integer
            attempted_length:
              type: integer
    CouldNotConstructFeesError:
      allOf:
        - "$ref": "#/components/schemas/TransactionBuildError"
        - type: object
          required:
            - attempts
          properties:
            attempts:
              type: integer
    TransactionFinalizeRequest:
      type: object
      required:
        - network
        - unsigned_transaction
        - signature
      properties:
        network:
          type: string
        unsigned_transaction:
          type: string
        signature:
          type: object
          required:
            - public_key
            - bytes
          properties:
            publicKey:
              type: string
            bytes:
              type: string
        submit:
          type: boolean
      example:
        network: mainnet
        unsigned_transaction: 07ef71a9d6c63444fce6abd2df8fab2755cfb51f6794e578f60d99337193811842000000020100210000000000000000000000000000000000000000000000000000ffcb9e57d4000002004506000403dc62fa04804f75d009a2fac32c8ceb9dc5eaccd54934fe20ef5b86be40c7a2ab0100000000000000000000000000000000000000000013da329a636aa8c02c00000008000002004506000403dc62fa04804f75d009a2fac32c8ceb9dc5eaccd54934fe20ef5b86be40c7a2ab0100000000000000000000000000000000000000000013da3298ae6ecf94cc8000020045060004038639dc49e14a94448045a3c595996282d8419eb9ae949dfb84b7bc48ba3d4fee0100000000000000000000000000000000000000000000000001b4fbd92b5f800000
        signature:
          public_key: 03dc62fa04804f75d009a2fac32c8ceb9dc5eaccd54934fe20ef5b86be40c7a2ab
          bytes: ''
    TransactionFinalizeResponse:
      type: object
      required:
        - transaction_identifier
        - signed_transaction
      properties:
        signed_transaction:
          type: string
        transaction_identifier:
          $ref: "#/components/schemas/TransactionIdentifier"
    TransactionSubmitRequest:
      type: object
      required:
        - network
        - signed_transaction
      properties:
        network:
          type: string
        signed_transaction:
          type: string
    TransactionSubmitResponse:
      type: object
      required:
        - transaction_identifier
      properties:
        transaction_identifier:
          $ref: "#/components/schemas/TransactionIdentifier"
    NetworkRequest:
      type: object
      example: {}
    NetworkResponse:
      type: object
      required:
        - network
        - ledger_state
      properties:
        network:
          type: string
        ledger_state:
          $ref: "#/components/schemas/LedgerState"
        target_ledger_state:
          $ref: "#/components/schemas/TargetLedgerState"
      example:
        network: mainnet
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        target_ledger_state:
          version: 1000
    TokenRequest:
      type: object
      required:
        - network
        - token_identifier
      properties:
        network:
          type: string
        token_identifier:
          "$ref": "#/components/schemas/TokenIdentifier"
      example:
        network: mainnet
        token_identifier:
          rri: xrd_rr1qy5wfsfh
    LedgerState:
      type: object
      required:
        - version
        - timestamp
        - epoch
        - round
      properties:
        version:
          type: integer
          format: int64
        timestamp:
          type: string
        epoch:
          type: integer
          format: int64
        round:
          type: integer
          format: int64
    TargetLedgerState:
      type: object
      required:
        - version
      properties:
        version:
          type: integer
          format: int64
    TokenResponse:
      type: object
      required:
        - ledger_state
        - token
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        token:
          type: array
          maxItems: 1
          items:
            "$ref": "#/components/schemas/Token"
      example:
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        token:
          - token_identifier:
              rri: xrd_rr1qy5wfsfh
            total_supply:
              token_identifier:
                rri: xrd_rr1qy5wfsfh
              value: '12014560679861300000000000000'
            info:
              total_burned:
                token_identifier:
                  rri: xrd_rr1qy5wfsfh
                value: '11437173800000000000000'
              total_minted:
                token_identifier:
                  rri: xrd_rr1qy5wfsfh
                value: '12014572117035100000000000000'
            properties:
              icon_url: https://assets.radixdlt.com/icons/icon-xrd-32x32.png
              is_supply_mutable: true
              symbol: xrd
              granularity: '1'
              name: Radix
              description: The Radix Public Network's native token, used to pay the
                network's required transaction fees and to secure the network through
                staking to its validator nodes.
              url: https://tokens.radixdlt.com
    TokenNativeRequest:
      type: object
      required:
        - network
      properties:
        network:
          type: string
      example:
        network: mainnet
    TokenNativeResponse:
      type: object
      required:
        - token
        - ledger_state
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        token:
          "$ref": "#/components/schemas/Token"
      example:
        ledger_state:
          epoch: 1
          round: 1
          version: 1
          timestamp: "2021-08-29T01:19:00.524Z"
        token:
          - token_identifier:
              rri: xrd_rr1qy5wfsfh
            supply:
              token_identifier:
                rri: xrd_rr1qy5wfsfh
              value: '12014560679861300000000000000'
            info:
              total_burned:
                token_identifier:
                  rri: xrd_rr1qy5wfsfh
                value: '11437173800000000000000'
              total_minted:
                token_identifier:
                  rri: xrd_rr1qy5wfsfh
                value: '12014572117035100000000000000'
            properties:
              icon_url: https://assets.radixdlt.com/icons/icon-xrd-32x32.png
              is_supply_mutable: true
              symbol: xrd
              granularity: '1'
              name: Radix
              description: The Radix Public Network's native token, used to pay the
                network's required transaction fees and to secure the network through
                staking to its validator nodes.
              url: https://tokens.radixdlt.com
    TokenDeriveRequest:
      type: object
      required:
        - network
        - creator_account_identifier
        - symbol
      properties:
        network:
          type: string
        creator_account_identifier:
          "$ref": "#/components/schemas/AccountIdentifier"
        symbol:
          type: string
      example:
        network: mainnet
        creator_account_identifier:
          address: rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88
        symbol: tkn
    TokenDeriveResponse:
      type: object
      required:
        - token_identifier
      properties:
        token_identifier:
          "$ref": "#/components/schemas/TokenIdentifier"
    TransactionStatusRequest:
      type: object
      required:
        - network
        - transaction_identifier
      properties:
        network:
          type: string
        transaction_identifier:
          $ref: "#/components/schemas/TransactionIdentifier"
      example:
        network: mainnet
        transaction_identifier:
          hash: ef71a9d6c63444fce6abd2df8fab2755cfb51f6794e578f60d99337193811842
    TransactionStatusResponse:
      type: object
      required:
        - ledger_state
        - transaction
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        transaction:
          type: array
          maxItems: 1
          items:
            "$ref": "#/components/schemas/AccountTransaction"
    ValidatorInfoRequest:
      type: object
      required:
        - network
        - validator_identifier
      properties:
        network:
          type: string
        validator_identifier:
          "$ref": "#/components/schemas/ValidatorIdentifier"
      example:
        network: mainnet
        validator_identifier:
          address: rv1qf2x63qx4jdaxj83kkw2yytehvvmu6r2xll5gcp6c9rancmrfsgfwttnczx
    ValidatorInfoResponse:
      type: object
      required:
        - ledger_state
        - validator
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        validator:
          "$ref": "#/components/schemas/Validator"
    ValidatorsRequest:
      type: object
      required:
        - network
      properties:
        network:
          type: string
      example:
        network: mainnet
    ValidatorsResponse:
      type: object
      required:
        - ledger_state
        - validators
      properties:
        ledger_state:
          "$ref": "#/components/schemas/LedgerState"
        validators:
          type: array
          items:
            "$ref": "#/components/schemas/Validator"
    InternalServerError:
      type: object
      properties:
        exception:
          type: string
        cause:
          type: string
    InvalidJsonError:
      type: object
      properties:
        cause:
          type: string
    InvalidRequestError:
      type: object
      properties:
        pointer:
          type: string
        cause:
          type: string
    UnexpectedError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      discriminator:
        propertyName: message
        mapping:
          INTERNAL_SERVER_ERROR: "#/components/schemas/InternalServerError"
          INVALID_JSON: "#/components/schemas/InvalidJsonError"
          INVALID_REQUEST: "#/components/schemas/InvalidRequestError"
    Validator:
      type: object
      required:
        - validator_identifier
        - stake
        - info
        - properties
      properties:
        validator_identifier:
          "$ref": "#/components/schemas/ValidatorIdentifier"
        stake:
          "$ref": "#/components/schemas/TokenAmount"
        info:
          "$ref": "#/components/schemas/ValidatorInfo"
        properties:
          "$ref": "#/components/schemas/ValidatorProperties"
      example:
        validator_identifier:
          address: rv1qf2x63qx4jdaxj83kkw2yytehvvmu6r2xll5gcp6c9rancmrfsgfwttnczx
        stake:
          token_identifier:
            rri: xrd_rr1qy5wfsfh
          value: '100000000000000000000'
        properties:
          url: https://learn.radixdlt.com/article/will-the-radix-foundation-operate-validator-nodes
          validator_fee: '100.0'
          name: Radix Foundation eu-west-1 node0 mainnet
          registered: true
          owner_account_identifier:
            address: rdx1qspldshtx0s2l2rcnaqtqpqz8vwps2y6d9se0wq25xrg92l66cmp6mcnc6pyu
          external_stake_accepted: false
        info:
          owner_stake:
            token_identifier:
              rri: xrd_rr1qy5wfsfh
            value: '0'
          uptime:
            epoch_range:
              from: 1
              to: 1
            uptime_percentage: '100.00'
            proposals_missed: 0
            proposals_completed: 108320
    ValidatorProperties:
      type: object
      required:
        - url
        - validator_fee
        - name
        - registered
        - owner_account_identifier
        - external_stake_accepted
      properties:
        url:
          type: string
        validator_fee:
          type: string
        name:
          type: string
        registered:
          type: boolean
        owner_account_identifier:
          "$ref": "#/components/schemas/AccountIdentifier"
        external_stake_accepted:
          type: boolean
    ValidatorInfo:
      type: object
      required:
        - owner_stake
        - uptime
      properties:
        owner_stake:
          "$ref": "#/components/schemas/TokenAmount"
        uptime:
          "$ref": "#/components/schemas/ValidatorUptime"
    ValidatorUptime:
      type: object
      required:
        - epoch_range
        - uptime_percentage
        - proposals_missed
        - proposals_completed
      properties:
        epoch_range:
          "$ref": "#/components/schemas/EpochRange"
        uptime_percentage:
          type: string
        proposals_missed:
          type: integer
          format: int64
          minimum: 0
        proposals_completed:
          type: integer
          format: int64
          minimum: 0
    EpochRange:
      type: object
      required:
        - from
        - to
      properties:
        from:
          type: integer
          format: int64
        to:
          type: integer
          format: int64
    Token:
      type: object
      required:
        - token_identifier
        - token_supply
        - info
        - token_properties
      properties:
        token_identifier:
          "$ref": "#/components/schemas/TokenIdentifier"
        token_supply:
          "$ref": "#/components/schemas/TokenAmount"
        info:
          "$ref": "#/components/schemas/TokenInfo"
        token_properties:
          "$ref": "#/components/schemas/TokenProperties"
      example:
        token_identifier:
          rri: xrd_rr1qy5wfsfh
        token_supply:
          token_identifier:
            rri: xrd_rr1qy5wfsfh
          value: '12014560679861300000000000000'
        info:
          total_burned:
            token_identifier:
              rri: xrd_rr1qy5wfsfh
            value: '11437173800000000000000'
          total_minted:
            token_identifier:
              rri: xrd_rr1qy5wfsfh
            value: '12014572117035100000000000000'
        token_properties:
          icon_url: https://assets.radixdlt.com/icons/icon-xrd-32x32.png
          is_supply_mutable: true
          symbol: xrd
          granularity: '1'
          name: Radix
          description: The Radix Public Network's native token, used to pay the network's
            required transaction fees and to secure the network through staking to
            its validator nodes.
          url: https://tokens.radixdlt.com
    TokenInfo:
      type: object
      required:
        - total_minted
        - total_burned
      properties:
        total_minted:
          "$ref": "#/components/schemas/TokenAmount"
        total_burned:
          "$ref": "#/components/schemas/TokenAmount"
    TokenProperties:
      type: object
      required:
        - symbol
        - is_supply_mutable
        - granularity
        - name
        - description
        - url
        - icon_url
      properties:
        name:
          type: string
        description:
          type: string
        icon_url:
          type: string
        url:
          type: string
        symbol:
          type: string
        is_supply_mutable:
          type: boolean
        granularity:
          "$ref": "#/components/schemas/BigInteger"
        owner:
          "$ref": "#/components/schemas/AccountIdentifier"
    AccountTransaction:
      type: object
      required:
        - transaction_status
        - transaction_identifier
        - actions
        - metadata
        - fee_paid
      properties:
        transaction_status:
          "$ref": "#/components/schemas/AccountTransactionStatus"
        transaction_identifier:
          "$ref": "#/components/schemas/TransactionIdentifier"
        actions:
          type: array
          items:
            "$ref": "#/components/schemas/Action"
        fee_paid:
          $ref: "#/components/schemas/TokenAmount"
        metadata:
          "$ref": "#/components/schemas/AccountTransactionMetadata"
    AccountTransactionStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - PENDING
            - CONFIRMED
            - FAILED
        confirmed_time:
          type: string
      example:
        status: CONFIRMED
        confirmed_time: 2021-07-27T17:35:10.726Z
    AccountTransactionMetadata:
      type: object
      required:
        - hex
      properties:
        hex:
          type: string
        message:
          type: string
    TokenAmount:
      type: object
      required:
        - value
        - token_identifier
      properties:
        value:
          "$ref": "#/components/schemas/BigInteger"
        token_identifier:
          "$ref": "#/components/schemas/TokenIdentifier"
    BigInteger:
      type: string
      pattern: "^-?[0-9]+$"
    AccountIdentifier:
      type: object
      required:
        - address
      properties:
        address:
          $ref: "#/components/schemas/AccountAddress"
    ValidatorIdentifier:
      type: object
      required:
        - address
      properties:
        address:
          $ref: "#/components/schemas/ValidatorAddress"
    TokenIdentifier:
      type: object
      required:
        - rri
      properties:
        rri:
          $ref: "#/components/schemas/ResourceIdentifier"
    TransactionIdentifier:
      type: object
      required:
        - hash
      properties:
        hash:
          type: string
          pattern: "^[0123456789abcdef]{64}$"
          maxLength: 64
          minLength: 64
    AccountAddress:
      type: string
      pattern: "^(r|t|d)dx[0-9]?1[023456789ACDEFGHJKLMNPQRSTUVWXYZacdefghjklmnpqrstuvwxyz]{6,69}$"
    ValidatorAddress:
      type: string
      pattern: "^(r|t|d)v[0-9]?1[023456789ACDEFGHJKLMNPQRSTUVWXYZacdefghjklmnpqrstuvwxyz]{6,69}$"
    ResourceIdentifier:
      type: string
      pattern: ^[!\"#$%&'()*+,-.\/0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\[\\\]\^_`abcdefghijklmnopqrstuvwxyz{|}~]{1,83}_r[rb]1[023456789ACDEFGHJKLMNPQRSTUVWXYZacdefghjklmnpqrstuvwxyz]{6,90}$
